# docker-compose run autobdd-run "--project ${BDD_PROJECT}"
# 
version: '3.5'
services:
  test-dev:
    image: "xyteam/autobdd-dev:1.0.3"
    container_name: webtest-example-dev
    shm_size: 1536M
    user: root
    privileged: true
    volumes:
      - ${HOME}/.ssh:/home/${USER}/.ssh:rw
      - ${HOME}/.m2:/home/${USER}/.m2:rw
      - ${HOME}/Projects/webtest-example:/home/${USER}/Projects/AutoBDD/test-projects/webtest-example:rw
      - ${HOME}/Projects/javatest-example:/home/${USER}/Projects/AutoBDD/test-projects/javatest-example:rw
    ports:
      - "5901:5900"
      - "2222:22"
    environment:
      USER: ${USER}
      PASSWORD: ${PASSWORD}
      VNC_PASSWORD: ${VNC_PASSWORD}
      RESOLUTION: 1920x1200
    entrypoint: ["/bin/bash", "/home/${USER}/Projects/AutoBDD/test-projects/webtest-example/docker/autobdd-dev.startup.sh"]

  test-run:
    image: "xyteam/autobdd-run:1.0.3"
    container_name: webtest-example-run
    shm_size: 1536M
    user: root
    privileged: true
    volumes:
      - ${HOME}/.ssh:/home/${USER}/.ssh:rw
      - ${HOME}/.m2:/home/${USER}/.m2:rw
      - ${HOME}/Projects/webtest-example:/home/${USER}/Projects/AutoBDD/test-projects/webtest-example:rw
      - ${HOME}/Projects/javatest-example:/home/${USER}/Projects/AutoBDD/test-projects/javatest-example:rw
    environment:
      USER: ${USER}
    entrypoint: ["/bin/bash", "/home/${USER}/Projects/AutoBDD/test-projects/webtest-example/docker/autobdd-run.startup.sh"]
